-- Active: 1725460092916@@127.0.0.1@5432@Constructora
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cargos
(
    id integer NOT NULL DEFAULT nextval('cargos_id_seq'::regclass),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT cargos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cliente
(
    id integer NOT NULL DEFAULT nextval('cliente_id_seq'::regclass),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    ap_paterno text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empleado_contratacion
(
    id integer NOT NULL DEFAULT nextval('empleado_contratacion_id_seq'::regclass),
    fecha_contratacion date NOT NULL,
    fecha_termino date,
    salario double precision NOT NULL,
    id_empleado integer NOT NULL,
    CONSTRAINT empleado_contratacion_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.empleados
(
    id integer NOT NULL DEFAULT nextval('empleados_id_seq'::regclass),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    ap_paterno text COLLATE pg_catalog."default" NOT NULL,
    id_cargo integer,
    CONSTRAINT empleados_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estatus
(
    id integer NOT NULL DEFAULT nextval('estatus_id_seq'::regclass),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    CONSTRAINT estatus_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.maquinarias
(
    id integer NOT NULL DEFAULT nextval('maquinarias_id_seq'::regclass),
    nombre text COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default" NOT NULL,
    id_proyecto integer,
    CONSTRAINT maquinarias_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.material_detalle
(
    id integer NOT NULL DEFAULT nextval('material_detalle_id_seq'::regclass),
    cantidad double precision NOT NULL,
    unidad_medida text COLLATE pg_catalog."default",
    precio_compra double precision,
    id_material integer NOT NULL,
    CONSTRAINT material_detalle_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.materiales
(
    id integer NOT NULL DEFAULT nextval('materiales_id_seq'::regclass),
    nombre text[] COLLATE pg_catalog."default" NOT NULL,
    descripcion text COLLATE pg_catalog."default",
    id_proveedor integer NOT NULL,
    id_status integer NOT NULL,
    CONSTRAINT materiales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proyecto_detalle
(
    id integer NOT NULL DEFAULT nextval('proyecto_detalle_id_seq'::regclass),
    id_proyecto integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_termino date,
    presupuesto double precision,
    ubicacion text COLLATE pg_catalog."default",
    CONSTRAINT proyecto_detalle_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proyecto_recursos_humanos
(
    id integer NOT NULL DEFAULT nextval('proyecto_recursos_humanos_id_seq'::regclass),
    id_empleado integer NOT NULL,
    id_proyecto integer,
    CONSTRAINT proyecto_recursos_humanos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proyectos
(
    id integer NOT NULL DEFAULT nextval('proyectos_id_seq'::regclass),
    descripcion text COLLATE pg_catalog."default",
    nombre_proyecto text COLLATE pg_catalog."default",
    id_cliente integer,
    id_status integer,
    CONSTRAINT proyectos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.proyectos_materiales
(
    id integer NOT NULL,
    id_proyecto integer NOT NULL,
    id_material integer NOT NULL,
    cantidad_material double precision NOT NULL,
    CONSTRAINT proyectos_materiales_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.empleado_contratacion
    ADD CONSTRAINT empleado_contratacion_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleado_contratacion
    ADD CONSTRAINT empleado_contratacion_id_empleado_fkey1 FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleados
    ADD CONSTRAINT empleados_id_cargo_fkey FOREIGN KEY (id_cargo)
    REFERENCES public.cargos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.empleados
    ADD CONSTRAINT empleados_id_cargo_fkey1 FOREIGN KEY (id_cargo)
    REFERENCES public.cargos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquinarias
    ADD CONSTRAINT maquinarias_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquinarias
    ADD CONSTRAINT maquinarias_id_proyecto_fkey1 FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.material_detalle
    ADD CONSTRAINT material_detalle_id_material_fkey FOREIGN KEY (id_material)
    REFERENCES public.materiales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.material_detalle
    ADD CONSTRAINT material_detalle_id_material_fkey1 FOREIGN KEY (id_material)
    REFERENCES public.materiales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_detalle
    ADD CONSTRAINT proyecto_detalle_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_detalle
    ADD CONSTRAINT proyecto_detalle_id_proyecto_fkey1 FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_recursos_humanos
    ADD CONSTRAINT proyecto_recursos_humanos_id_empleado_fkey FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_recursos_humanos
    ADD CONSTRAINT proyecto_recursos_humanos_id_empleado_fkey1 FOREIGN KEY (id_empleado)
    REFERENCES public.empleados (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_recursos_humanos
    ADD CONSTRAINT proyecto_recursos_humanos_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyecto_recursos_humanos
    ADD CONSTRAINT proyecto_recursos_humanos_id_proyecto_fkey1 FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_id_cliente_fkey1 FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_id_status_fkey FOREIGN KEY (id_status)
    REFERENCES public.estatus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos
    ADD CONSTRAINT proyectos_id_status_fkey1 FOREIGN KEY (id_status)
    REFERENCES public.estatus (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos_materiales
    ADD CONSTRAINT proyectos_materiales_id_material_fkey FOREIGN KEY (id_material)
    REFERENCES public.materiales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos_materiales
    ADD CONSTRAINT proyectos_materiales_id_material_fkey1 FOREIGN KEY (id_material)
    REFERENCES public.materiales (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos_materiales
    ADD CONSTRAINT proyectos_materiales_id_proyecto_fkey FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.proyectos_materiales
    ADD CONSTRAINT proyectos_materiales_id_proyecto_fkey1 FOREIGN KEY (id_proyecto)
    REFERENCES public.proyectos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;