-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Empresa"
(
    "RUT" character NOT NULL,
    "Nombre" text NOT NULL,
    "Dirección" character varying NOT NULL,
    "Telefono" numeric NOT NULL,
    "Correo" character varying NOT NULL,
    "Web" character varying,
    PRIMARY KEY ("RUT")
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    "Rut" character NOT NULL,
    "Nombre" text NOT NULL,
    "Correo" character varying NOT NULL,
    "Direccion" character varying NOT NULL,
    "Celular" numeric NOT NULL,
    "Alta" text NOT NULL,
    PRIMARY KEY ("Rut")
);

CREATE TABLE IF NOT EXISTS public."TipoVehículo"
(
    "IdTipoVehiculo" serial NOT NULL,
    "Nombre" text NOT NULL,
    PRIMARY KEY ("IdTipoVehiculo")
);

CREATE TABLE IF NOT EXISTS public."Mantencion"
(
    "IDMantencion" serial NOT NULL,
    "Fecha" date NOT NULL,
    "TrabajosRealizados" text NOT NULL,
    "IdVenta" integer NOT NULL,
    PRIMARY KEY ("IDMantencion")
);

CREATE TABLE IF NOT EXISTS public."Venta"
(
    "Folio" serial NOT NULL,
    "Fecha" date NOT NULL,
    "Monto" double precision NOT NULL,
    "RUTCliente" character NOT NULL,
    PRIMARY KEY ("Folio")
);

CREATE TABLE IF NOT EXISTS public."Marca"
(
    "IDMarca" serial NOT NULL,
    "Nombre" text NOT NULL,
    PRIMARY KEY ("IDMarca")
);

CREATE TABLE IF NOT EXISTS public."Vehiculo"
(
    "IDVehiculo" serial NOT NULL,
    "Patente" character varying NOT NULL,
    "Marca" character varying NOT NULL,
    "Modelo" character varying NOT NULL,
    "Color" text NOT NULL,
    "Precio" double precision NOT NULL,
    "FrecuenciaMantencion" numeric NOT NULL,
    "IDTipoVehículo" integer NOT NULL,
    "IDVenta" integer NOT NULL,
    "IDMarca" integer NOT NULL,
    PRIMARY KEY ("IDVehiculo")
);

ALTER TABLE IF EXISTS public."Mantencion"
    ADD FOREIGN KEY ("IdVenta")
    REFERENCES public."Venta" ("Folio") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Venta"
    ADD FOREIGN KEY ("RUTCliente")
    REFERENCES public."Cliente" ("Rut") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehiculo"
    ADD FOREIGN KEY ("IDTipoVehículo")
    REFERENCES public."TipoVehículo" ("IdTipoVehiculo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehiculo"
    ADD FOREIGN KEY ("IDVenta")
    REFERENCES public."Venta" ("Folio") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehiculo"
    ADD FOREIGN KEY ("IDMarca")
    REFERENCES public."Marca" ("IDMarca") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;