-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    rut character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default",
    correo character varying(80) COLLATE pg_catalog."default",
    direccion character varying(120) COLLATE pg_catalog."default",
    celular character varying(15) COLLATE pg_catalog."default",
    alta character(1) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public."Empresa"
(
    rut character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default",
    direccion character varying(120) COLLATE pg_catalog."default",
    telefono character varying(15) COLLATE pg_catalog."default",
    correo character varying(80) COLLATE pg_catalog."default",
    web character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT empresa_pkey PRIMARY KEY (rut)
);

CREATE TABLE IF NOT EXISTS public.mantencion
(
    idmantencion numeric(12, 0) NOT NULL,
    fecha date,
    trabajosrealizados character varying(1000) COLLATE pg_catalog."default",
    venta_folio numeric(12, 0),
    CONSTRAINT mantencion_pkey PRIMARY KEY (idmantencion)
);

CREATE TABLE IF NOT EXISTS public.marca
(
    idmarca numeric(12, 0) NOT NULL,
    nombre character varying(120) COLLATE pg_catalog."default",
    CONSTRAINT marca_pkey PRIMARY KEY (idmarca)
);

CREATE TABLE IF NOT EXISTS public.tipovehiculo
(
    idvehiculo numeric(12, 0) NOT NULL,
    nombre character varying(120),
    CONSTRAINT tipovehiculo_pkey PRIMARY KEY (idvehiculo)
);

CREATE TABLE IF NOT EXISTS public.vehiculo
(
    idvehiculo numeric(12, 0) NOT NULL,
    patente character varying(10) COLLATE pg_catalog."default",
    marca character varying(20) COLLATE pg_catalog."default",
    modelo character varying(15) COLLATE pg_catalog."default",
    color character varying(15) COLLATE pg_catalog."default",
    precio numeric(12, 0),
    frecuenciamantencion numeric(5),
    marca_idmarca numeric(12, 0),
    tipovehiculo_idtipovehiculo numeric(12, 0),
    CONSTRAINT vehiculo_pkey PRIMARY KEY (idvehiculo)
);

CREATE TABLE IF NOT EXISTS public.venta
(
    folio numeric(12, 0) NOT NULL,
    fecha date,
    monto numeric(12, 0),
    vehiculo_idvehiculo numeric(12, 0),
    cliente_rut character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT venta_pkey PRIMARY KEY (folio)
);

ALTER TABLE IF EXISTS public.mantencion
    ADD FOREIGN KEY (venta_folio)
    REFERENCES public.venta (folio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehiculo
    ADD FOREIGN KEY (marca_idmarca)
    REFERENCES public.marca (idmarca) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehiculo
    ADD FOREIGN KEY (tipovehiculo_idtipovehiculo)
    REFERENCES public.tipovehiculo (idvehiculo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT venta_cliente FOREIGN KEY (cliente_rut)
    REFERENCES public.cliente (rut) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.venta
    ADD CONSTRAINT venta_vehiculo FOREIGN KEY (vehiculo_idvehiculo)
    REFERENCES public.vehiculo (idvehiculo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;