-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estudiante
(
    id_estudiante serial NOT NULL,
    nombre text NOT NULL,
    apellido text NOT NULL,
    fecha_nacimiento date NOT NULL,
    PRIMARY KEY (id_estudiante)
);

CREATE TABLE IF NOT EXISTS public."Curso"
(
    id_curso integer NOT NULL,
    nombre_curso integer NOT NULL,
    costo double precision,
    PRIMARY KEY (id_curso)
);

CREATE TABLE IF NOT EXISTS public."Pago"
(
    id_pago integer NOT NULL,
    id_estudiante integer NOT NULL,
    monto double precision NOT NULL,
    fecha_pago date NOT NULL,
    metodo_pago text NOT NULL,
    id_curso integer NOT NULL,
    PRIMARY KEY (id_pago)
);

ALTER TABLE IF EXISTS public."Pago"
    ADD FOREIGN KEY (id_estudiante)
    REFERENCES public.estudiante (id_estudiante) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Pago"
    ADD FOREIGN KEY (id_curso)
    REFERENCES public."Curso" (id_curso) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;