-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Clientes"
(
    "Id_cliente" serial NOT NULL DEFAULT nextval('"Clientes_id_cliente_seq"'::regclass),
    "Nombre" text COLLATE pg_catalog."default" NOT NULL,
    "Apellido" text NOT NULL,
    "Direccion" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Clientes_pkey" PRIMARY KEY ("Id_cliente")
);

CREATE TABLE IF NOT EXISTS public."Productos"
(
    "Id_Productos" serial NOT NULL,
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    PRIMARY KEY ("Id_Productos")
);

CREATE TABLE IF NOT EXISTS public."Tipo_Transacciones"
(
    "Id" serial NOT NULL,
    "Nombre" text,
    "Descripcion" text,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.transacciones
(
    "Id" serial NOT NULL,
    "Id_cliente" integer NOT NULL,
    "Id_producto" integer NOT NULL,
    "Id_tipo_transacciones" integer NOT NULL,
    "Fecha" date NOT NULL,
    "Cantidad" integer NOT NULL,
    "Precio" double precision NOT NULL,
    PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public.transacciones
    ADD FOREIGN KEY ("Id_cliente")
    REFERENCES public."Clientes" ("Id_cliente") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transacciones
    ADD FOREIGN KEY ("Id_producto")
    REFERENCES public."Productos" ("Id_Productos") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transacciones
    ADD FOREIGN KEY ("Id_tipo_transacciones")
    REFERENCES public."Tipo_Transacciones" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;